26. input obat fe
tata-01/apotek-FE pull request #1
Opened 2023-12-21 07:58 UTC by agustianawardani

![image](https://github.com/tata-01/apotek-FE/assets/129156069/a2569e74-0263-457a-b4fb-1989f7b94d0e)

2023-12-22 06:11 UTC, Mythicomyia requested changes
ganti le .php

2023-12-22 07:54 UTC, agustianawardani commented
@Mythicomyia

2023-12-23 16:16 UTC, Mythicomyia requested changes
tolong ulangi supaya file dashbord ga ke tukar

2023-12-23 16:16 UTC, Mythicomyia commented on dasboard/dasboard.html
ini kenapa di rubah rubah ?

2023-12-23 16:24 UTC, closed without merging